TACC-Cloud/hazmapper

src/app/components/control-bar/control-bar.component.html, src/app/components/control-bar/control-bar.component.ts, src/app/services/geo-data.service.ts, src/app/services/notifications.service.ts
Provides visual feedback with a spinner when importing files, especially large files that take a long time.
* [DES-1761](https://jira.tacc.utexas.edu/browse/DES-1761)
Added a `loadingData` observable to keep track of loading state.
Set it to false by default and true on `import*` functions in `geo-data.service`.
Then, once the `getRecent` poll returns a success, loading state is back to false.
1. Open Hazmapper and login.
2. Import a layer, point cloud, or a file through the assets panel.
3. Confirm that spinner shows on the top left section of the control bar.
I wasn't sure where the best place to put the loading state. So, I just put it in `notifications.service`.
=> DES-1761 - Loader/spinner to notify user that features are being fetched.

src/app/components/file-browser/file-browser.component.html, src/app/components/file-browser/file-browser.component.styl, src/app/components/file-browser/file-browser.component.ts
Implements traditional OS gui file browser mouse selection behavior in the `file-browser-component`.
* [DES-1845](https://jira.tacc.utexas.edu/browse/DES-1845)
1. [X] Change regular `Click` select to not toggle selection in file-browser-component.
2. [X] `Ctrl-Click` allows the previous behavior.
3. [X] `Shift-Click` allows ranged selections (both down and up).
4. [X] `Shift-Ctrl-Click` allows aggregate ranged selections.
5. Referenced other details from OS File Manager (Windows File Explorer, Gnome Nautilus)
1. Test that each selection mechanisms work.
=> TASK/DES-1845 - Add mouse multi-select.

Dockerfile, src/index.html
Fix broken routing in staging deployment by fixing our staging/production docker image
* [DES-1934](https://jira.tacc.utexas.edu/browse/DES-1934)
Removed use of `--base-href` in ng build
Set base href dynamically based on hostname/path
Image (taccaci/hazmapper:41ad336) has been deployed and being used at hazmapper.tacc.utexas.edu/staging
1.  go to hazmapper.tacc.utexas.edu/staging
2. navigate to a project
3. reload on project and confirm that works
4. try other things?
I made minor change to `nginx.conf` on hazmapper.tacc.utexas.edu
=> Task/DES-1934 Fix broken routing in staging deployment

.travis.yml, kube/Makefile
This PR updates deployment steps:
* removes use of travis-ci to push images to dockerhub (not being done in Jenkins https://jenkins01.tacc.utexas.edu/view/Hazmapper+Geoapi/)
* fixes issue where kubectl apply wasn't using the correct prod/staging kube context.
* [DES-1950](https://jira.tacc.utexas.edu/browse/DES-1950)
=> DES-1950 update deployment steps

kube/Makefile
Follow on to DES-1950:  There was a missing deletion of the hazmapper service.
* [DES-1950](https://jira.tacc.utexas.edu/browse/DES-1950)
=> Fix missing delete of hazmapper service

src/app/components/users-panel/users-panel.component.ts, src/app/services/env.service.ts
Makes desginsafe link to point to corresponding staging/production versions.
* [DES-1936](https://jira.tacc.utexas.edu/browse/DES-1936)
Added a portal variable env.service.ts
1. Ensure that saved links work differently in different environments.
I wasn't sure what to set the development environment's link to. I set it to point to staging for now.
=> Make designsafe link dynamic (staging/production).

src/app/components/map/map.component.ts, src/app/models/models.ts, src/app/models/style.ts, src/app/utils/leafletUtils.ts
Adds ability to detect style properties in a feature and display it on the map.
* [DES-2006](https://jira.tacc.utexas.edu/browse/DES-2006)
Changed `leafletUtils.ts` to add custom marker creators and changed some lines to remove eslint/tslint warnings.
~~1. Try to put something like the below after line 150 in `map.component.ts`~~
~~2. Check that it loads the colors/icon~~
~~3. Also try it without the icon property and change `d.properties.customMarker` to `'styled'`~~
~~4. This should show a circle marker with the style applied to it.~~
Import files under `version 2` from https://www.designsafe-ci.org/data/browser/projects/3676202356334531051-242ac117-0001-012/
=> Task/DES-2006: Add ability to display custom styles and icons on map.

src/app/components/control-bar/control-bar.component.ts, src/app/components/file-browser/file-browser.component.ts, src/app/components/main-welcome/main-welcome.component.styl, src/app/components/main-welcome/main-welcome.component.ts, src/app/components/modal-create-project/modal-create-project.component.html, src/app/components/modal-create-project/modal-create-project.component.styl, src/app/components/modal-create-project/modal-create-project.component.ts, src/app/components/modal-link-project/modal-link-project.component.html, src/app/components/modal-link-project/modal-link-project.component.ts, src/app/components/user-row/user-row.component.html, src/app/components/user-row/user-row.component.ts, src/app/components/users-panel/users-panel.component.html, src/app/components/users-panel/users-panel.component.ts, src/app/models/models.ts, src/app/models/rapid-project-request.ts, src/app/services/agave-systems.service.ts, src/app/services/geo-data.service.ts, src/app/services/projects.service.ts, src/app/utils/leafletUtils.ts
* [DES-2001](https://jira.tacc.utexas.edu/browse/DES-2001)
When saving/linking the map to a project, ensure that an observable project is also created.
1. Save a map to a project and ensure that users are synced.(test with TACC-cloud/geoapi#65)
=> Task/DES-2001: Project links as observables (subscribe to project-user data).

src/app/services/projects.service.ts
Currently there is a bug when trying to update a project (e.g. for renaming).
This bug  was probably introduced when I was trying to implement the save-as functionality, which will be addressed in [DES-2157](https://jira.tacc.utexas.edu/browse/DES-2157).
Remove delete/save file when updating project.
1. Update the project (e.g. rename).
2. Ensure that there is no error.
=> Remove delete/save file when updating project.

src/app/components/main-welcome/main-welcome.component.html, src/app/models/models.ts, src/app/services/projects.service.ts
Adds a spinner notification when deleting maps to indicate progress.
* [DES-2165](https://jira.tacc.utexas.edu/browse/DES-2165)
Now when deleting a map, we redirect to the welcome page first and then show the spinner to wait on the deletion of the map.
1. Try deleting a map with many assets. Or maybe insert `sleep()` in the geoapi project delete endpoint.
2. When deleting from the "Manage Panel", ensure that you are redirected to the "Welcome" page.
3. Ensure that you see a spinner before the project is deleted.
4. Repeat steps 2-3 for deleting the project from the "Welcome" page.
5. Ensure that error status is shown when error is given (raise ApiException from the geoapi project delete endpoint).
6. Ensure that the error status is shown in the welcome page.
=> Add spinner to welcome list item on deletion in progress.

src/app/components/main-welcome/main-welcome.component.html, src/app/components/modal-create-project/modal-create-project.component.html, src/app/components/modal-create-project/modal-create-project.component.ts, src/app/services/projects.service.ts
When selecting `..` from a single level below the root path of a system (i.e. a from a folder in root), the `system_path` would be an empty string.
Furthermore, the welcome page was checking against the existence of `system_path`, where it just needed to check that it is a project system.
* [DES-2167](https://jira.tacc.utexas.edu/browse/DES-2167)
1. Changed the `system_path` to revert to root path `'/'` if the selected path is empty.
1. Set the `AppEnvironment` `backend` to `EnvironmentType.Production` in `environment.ts`.
2. Ensure that the **GEER_Marshall Fire, Colorado** project correctly shows the project information in the welcome page.
3. Ensure that, when creating a project, the page selecting the `..` from a inside a folder located in the root path gives you a `/` for the root …
=> Bug/DES-2167: Associated project is not shown with map

src/app/components/main-welcome/main-welcome.component.html, src/app/services/projects.service.ts
There is an error when trying to render older projects in the `welcome-page` component.
Older projects do not have a `systemId`. So this adds a check to that.
N/A
1. Ensure that you do not have an error when you have older projects on your welcome page projects list.
=> Fix systemId rendering bug.

package-lock.json, package.json, src/app/components/map/map.component.ts, src/app/components/modal-create-tile-server/modal-create-tile-server.component.html
Adds ArcGIS tile layer support to hazmapper.
* [DES-2183](https://jira.tacc.utexas.edu/browse/DES-2183)
Added `esri-leaflet` and `@types/esri-leaflet` and hooked them up to the tile layer system.
1. Go to "Layers"
2. Click "+" to add a layer
3. Select "Manual" as the "Import Method"
4. Select  "ArcGIS" as the "Server Type"
5. Give it an arbitrary "Name"
6. Apply following urls
- https://services.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer (A basemap)
- https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/RPD1085_Map/MapServer (Colorado data: This will be around Louisville, Colorado, it's really hard to find it. you might want to keep just the "Road" basemap displayed).
7. Ensure that they show up and interact correctly with other layers.
There is no …
=> Task/DES-2183: Add ArcGIS tile layer support to hazmapper.

src/app/components/filters-panel/filters-panel.component.html, src/app/components/filters-panel/filters-panel.component.ts, src/app/constants/assets.ts, src/app/models/models.ts, src/app/services/filter.service.ts
Change asset filter interface so that all filter types are initially selected (checkbox behavior rather than radio, see image).
* [DES-2185](https://jira.tacc.utexas.edu/browse/DES-2185)
Added an `enabledAssetTypes` array in the `filters-service` and changed the query to the server to be a comma separated string.
1. Test with TACC-Cloud/geoapi#76
2. Ensure that, on initial load, the assets are all displayed correctly.
3. Ensure that each asset type is filtered out when unselected.
=> Bug/DES-2185: Fix filtering query.

src/app/components/map/map.component.ts, src/app/constants/tile-servers.ts, src/app/models/models.ts
Allow users to zoom further in tms tiles and arcgis tiles.
* [DES-2215](https://jira.tacc.utexas.edu/browse/DES-2215)
Set `maxNativeZoom` and `maxZoom` to allow users to zoom further than before.
1. Try testing with https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/RPD1085_Map/MapServer
2. Ensure that the map doesn't disappear after zooming beyond zoom level 19.
=> Bug/DES-2215: Adjust tile server zoom levels

angular/src/app/app.module.ts, angular/src/app/components/file-tree-node/file-tree-node.component.html, angular/src/app/components/file-tree-node/file-tree-node.component.styl, angular/src/app/components/file-tree-node/file-tree-node.component.ts, angular/src/app/components/map/map.component.ts
Added virtual rendering of lists to speed up assets panel.
* [DES-2309](https://jira.tacc.utexas.edu/browse/DES-2309)
Added virtual rendering of long lists (>500) so that they are incrementally rendered rather than all at once.
1. Test problematic map with Production environment 
- http://hazmapper.local:4200/project/14a916d2-b3eb-454d-b4f5-9a0d98b844d3
2. Ensure that opening the assets panel does not cause the main slowdown
=> Task/DES-2309: Add virtual list rendering.

angular/package-lock.json, angular/package.json, angular/src/app/components/map/map.component.ts
This PR fixes zoom level on the project load and also when selecting asset.
Hazmapper fits to project bounds when loading and fits a single asset bound when the asset is selected which for points can be the max zoom of our entire map which is too high.  Now, we have max zoom of 18 when zooming to assets or to the entire project.
* [WG-79](https://jira.tacc.utexas.edu/browse/WG-79)
1. set `angular/src/environments/environment.ts` set `backend` to EnvironmentType.Production or EnvironmentType.Staging
`npm run start:local`
2. Go to http://hazmapper.local:4200/
3. Find project with asset
4. Click on an asset and confirm zoom isn't as close as what you would see when viewing the project hazmapper.tacc.utexas.edu/hazmapper
5. OIf the project has just one asset, you can also confirm that when it …
=> Task/WG-79: fix zoom level

angular/src/app/components/assets-panel/assets-panel.component.html, angular/src/app/components/feature-row/feature-row.component.html, angular/src/app/components/feature-row/feature-row.component.ts, angular/src/app/components/file-tree-node/file-tree-node.component.html, angular/src/app/components/file-tree-node/file-tree-node.component.ts
Remove asset delete button when viewing public view of map.
* [WG-78](https://jira.tacc.utexas.edu/browse/WG-78)
1. Load a map
2. See that the delete button is available for the selected asset
3. Load the public version of map, and ensure that delete button is NOT there for the selected asset
Private view with delete button
Public view WITHOUT delete button
=> task/WG-78: remove asset delete button from public map view

Makefile, angular/src/app/services/env.service.ts, angular/src/environments/environmentType.ts
Add dev server as option for backend
* [WG-155](https://jira.tacc.utexas.edu/browse/WG-155)
1.
=> task/WG-155: Add dev server as option for backend

angular/src/app/components/asset-detail/asset-detail.component.html
Remove the duplicate download button for images
Regression probably in merge conflict in https://github.com/TACC-Cloud/hazmapper/pull/118
None
1. View image panel on right for a selected image asset and confirm just one download button.
=> Remove duplicate download button

angular/src/index.html
Added new Google Analytics 4 tracking property MeasurementID for hazmapper in the base template page.
- [WG-143](https://jira.tacc.utexas.edu/browse/WG-143)
- Changed the GA4 code measurementID value.
1. Build and run project.
2. Verify new GA4 code is in all page templates. 
- None
- None
=> Hazmapper PROD GA4 MeasurementID

angular/src/app/app.interceptors.ts
Add uuid for guest users:
* create uuid for guest user in local storage
* add that uuid to header of requests to geoapi
* [WG-139](https://jira.tacc.utexas.edu/browse/WG-139)
See https://github.com/TACC-Cloud/geoapi/pull/155 for testing steps.
=> task/WG-139: add uuid for guest users

angular/src/app/components/modal-questionnaire-viewer/modal-questionnaire-viewer.component.ts, angular/src/app/services/geo-data.service.ts, angular/src/app/utils/questionnaireBuilder.ts
Show asset image alongside the question in the questionnaire
* [WG-173](https://jira.tacc.utexas.edu/browse/WG-173)
1. Use geoapi `feature/questionnaire` when running hazmapper
2. Add an example questionnaire from  "Questionnaire_Example".  
4. See that one questionnaire is imported correctly. and that its asset images are showed along questions inside the modal.
=> task/WG-173:show asset image alongside question in the questionnaire

angular/src/app/app.interceptors.ts
This PR adds the application information (i.e. "taggit", "hazmapper") to the request header to be used by the backend for analytics-related logging. See https://github.com/TACC-Cloud/geoapi/pull/161 for more details.
* [WG-140](https://jira.tacc.utexas.edu/browse/WG-140)
See https://github.com/TACC-Cloud/geoapi/pull/161
=> task/WG-140: add app information to request for analytics-related logging

angular/src/app/components/modal-questionnaire-viewer/modal-questionnaire-viewer.component.styl
A quick tweak to the Sub-question styling to clean it up a little and add some padding.
* None.
1. Build and run if needed.
Before:
- ![chrome_NuSw4tX0xj](https://github.com/TACC-Cloud/hazmapper/assets/3238078/7c75bf59-0473-45fe-980b-a527b2fb7dfa)
After:
- ![chrome_Nt6bkXPLvG](https://github.com/TACC-Cloud/hazmapper/assets/3238078/cda51d01-e52f-44bd-90dd-6e4f73f0aabc)
None.
=> Questionnaire Style Tweak

angular/src/app/components/asset-detail/asset-detail.component.styl
With the questionnaire modal open, you could still click "View Questionnaire" button multiple times. This caused multiple modals to be opened on top of each other and a darkening of the screen. The issue was that the right panel (containing the "View Questionnaire" button) had a z-index value higher than the modal's z-index.  This is fixed in this PR.
* [WG-172](https://jira.tacc.utexas.edu/browse/WG-172)
0. (optional) use staging environment for backend (i.e. edit `angular/src/environments/environment.ts` to use `backend: EnvronmentType.Staging`) 
1. Choose a map with a questionnaire.
2. Ensure you can no longer click View Questionnaire multiple times.
=> task/WG-172: stop "View Questionnaire" button from being pushed multiple times

angular/src/app/components/asset-detail/asset-detail.component.html
Rework asset detail component so questionnaires are treated uniquely.  Questionnaires and asset previews are given full space of the detail component and metadta/geography are not shown. 
* [WG-175](https://tacc-main.atlassian.net/browse/WG-175)
=> Rework layout of questionnaire to take all space

angular/src/app/components/dock/dock.component.html, angular/src/app/components/layers-panel/layers-panel.component.html, angular/src/app/components/layers-panel/layers-panel.component.ts
During the RAPID webinar, users wanted to be able to tweak public map opacity without making changes to the map.
also from Karen (https://designsafe-ci.slack.com/archives/C057MKDUZFS/p1683657846684769?thread_ts=1683649659.461539&cid=C057MKDUZFS):
It may also be helpful to keep some format of the layers option so users can still toggle between the satellite view and the map view. That way they can see what an area looked like before the event?
* [WG-91](https://jira.tacc.utexas.edu/browse/WG-91)
- Project Owners will still be able to add tile layers, add overlays, edit tile layer names, change opacity, delete tile layers and delete overlays.
- However, now when project owners make their maps "public", the guest/user will be able to:
1. See the Layers Option
2. Tweak the opacity of a tile …
=> task/WG-91-Allow non-persistent tile layer adjustments in public hazmapper maps

angular/src/app/app.interceptors.ts
Disable added headers and use query params on single route instead. Headers can't be used due to https://tacc-main.atlassian.net/browse/WG-191 . The use of headers is left in code but commented out; to be re-used in WG-192 when we start using Taips V3.
See https://github.com/TACC-Cloud/geoapi/pull/161 for more details.
* [WG-140](https://tacc-main.atlassian.net/browse/WG-140)
* [WG-191](https://tacc-main.atlassian.net/browse/WG-191)
See https://github.com/TACC-Cloud/geoapi/pull/161
=> task/WG-191: do not use headers for analytics information due to WG-191

react/.eslintignore, react/.eslintrc.json, react/package.json, react/src/pages/MapProject/MapProject.tsx, react/src/utils/authUtils.ts, react/vite.config.ts
Improve linting:
* updated linting rules
* made some minor fixes of existing code
* added eslintignore
* [WG-197](https://tacc-main.atlassian.net/browse/WG-197)
1.  Just see output on CI
=> task/WG-197: improve linting on react project

react/package.json, react/postcss.config.cjs, react/vite.config.ts
Addressed CSS minifying warnings by adding postcss config file that is based off of TUP's yaml file. Added some code to vite config to deal with build and chunk size issues. 
* [WG-216](https://tacc-main.atlassian.net/browse/WG-216)
- Created postcss.config.cjs file that allows vite to understand how to deal with css minifying warnings and nesting. 
- Updated vite.config.ts file to handle build and chunk size warnings during 'npm run build' command.
- Updated chunk size limit to 700.
- For optimization (regarding the chunk size warning) I created a conditional in vite.config.ts file that will separate all third-party node modules into a separate 'vendor' group. This will help with loading. 
- Added additional code (got this from CEP codebase) to the package.json file that specifies the …
=> task/WG-216: addressing css minifying warnings

angular/src/app/fixtures/projectv3.fixture.ts, angular/src/app/services/agave-systems.service.ts
Jake provided a example of the new DS v3 project response. Because there is no v3 designsafe portal, yet, we needed to mock a response so we could get a listing of projects (each is its own system) from a UI standpoint when creating a new map. 
* [WG-261](https://tacc-main.atlassian.net/browse/WG-261)
- Created a projectv3.fixture.ts file that represents a project (project system) response that will come from the /api/projects endpoint once the v3 DS portal is up and running. 
- Added code to use the mock fixture so that the project would show under 'My Projects' in the dropdown when creating a new map and selecting a system to save the map. 
1. For the backend, run local on the feature/tapisv3 branch
2. Run with angular hazmapper
3. Click the Create a Map button so the modal appears
4. …
=> task/WG-261: mock v3 project designsafe

react/package-lock.json, react/src/components/CreateMapModal/CreateMapModal.tsx
In an effort to match angular hazmapper's mirroring feature (initially typing in the map name also populated the custom file name field), I mimicked that feature in react hazmapper.  
* [WG-249](https://tacc-main.atlassian.net/browse/WG-249)
- Added useEffect hook to watch changes in the map name and system file fields (name and custom file name)
- Now if the user types in the Name field, the Custom File Name will mirror the value, initially. However, if the user wants to make the Custom File Name different than the Map name, they can manually edit the Custom File Name field to do so.
- The Name field should be allowed to have spaces in the map name--however the Custom File Name field is not allowed to have spaces--so I added code to replace spaces to underscores in the Custom File Name …
=> task/WG-249: Mirror map name and file name initially

react/src/components/CreateMapModal/CreateMapModal.module.css, react/src/components/CreateMapModal/CreateMapModal.tsx
* [WG-264](https://tacc-main.atlassian.net/browse/WG-264)
- Before this PR, the .hazmapper extenion was being pushed out of the input box every time the "File name required" text was rendered from the Yup validation.
- Now the hazmapper extension will stay inside the input box when the validation text appears, making the UI look cleaner. 
1. Run with local geoapi backend (master branch is fine)
2. Open the "Create Map" modal
3. Verify that the ".hazmapper" extension is present in the Custom File Name field
4. Start typing a file name in that field, then delete the text and click out/unfocus from the Custom File Name field so that the "File name is required" text pops up. 
5. When it does, verify that the ".hazmapper" extension text is still inside the input box 
6. Compare with the …
=> task/WG-264: Hazmapper suffix fix

react/src/components/Projects/ProjectListing.tsx, react/src/pages/MainMenu/MainMenu.tsx
* [WG-276](https://tacc-main.atlassian.net/browse/WG-276)
- Moved the Create Map button and comp/modal callback from the MainMenu to the ProjectListing comp.
1. Run React hazmapper client (production is fine to run as the backend) and go to localhost:4200. 
2. Click the "Create a New Map" button (now in the ProjectListings comp) and make sure the modal comes up as expected.
=> task/WG-276: Moving Create Map Button to ProjectListings

angular/src/app/components/users-panel/users-panel.component.ts, angular/src/app/models/models.ts, angular/src/app/services/agave-systems.service.ts, angular/src/app/services/env.service.ts, angular/src/environments/environment.ts
* [WG-274](https://tacc-main.atlassian.net/browse/WG-274)
- Using ds_id instead of system_id in the Users panel because Designsafe-Next uses PRJ in its URL rather than the system uuid like previously. (Related to the two links in the Manage, Save tab on user panel)
- Updated code to match structure of response data, as well as the URLs where the request are made on the new DS Next site
- DesignsafeURL and Portal URL now use DS Next.
- Projects request endpoint is now appropriately updated for new DS Next site. 
1. 
Waiting for nginx conf to be merged for DS Next before merging this PR.
=> task/WG-274: Update projects for next

angular/src/app/services/env.service.ts
We've updated hazmapper.tacc.utexas.edu to route all backend requests to the geoapi-services VMs.  This updates the client to use the same routes.
* [WG-257](https://tacc-main.atlassian.net/browse/WG-275)
1. We tested with local client using experimental backend
=> task/WG-275: update routes for backend geoapi to use hazmapper.tacc.utexas.edu

angular/src/app/components/file-browser/file-browser.component.ts
* [WG-287](https://tacc-main.atlassian.net/browse/WG-287)
- Added a condition where the `..` backPath folder is only added in the first load when the offset is 0 
- Made a change so that the `..` backPath is added to the `filesList` array instead of the `files` array from the api response. Originally, the change in length from the added backPath entry was causing the offset to be 1 larger than expected which broke the infinite scroll functionality
1. Start the Angular application and open the file browser modal by selecting `Import from DesignSafe` under Assets
2. Select a system with lots of files/folders (`Published Data` has hundreds)
3. Scroll the listing and ensure that the listing works smoothly and there are no duplicate `..` folders. Can also monitor the Network tab to ensure new …
=> task/WG-287 - File listing fix hazmapper

angular/src/app/app-routing.module.ts, angular/src/app/app.interceptors.ts, angular/src/app/app.module.ts, angular/src/app/components/callback/callback.component.ts, angular/src/app/models/models.ts, angular/src/app/services/authentication.service.ts, angular/src/app/services/notifications.service.ts
Use geoapis new auth endpoints instead of authing with tapis.
Note: updating the key were we store this in local storage so not accidentally get a v3 token
* [WG-268](https://tacc-main.atlassian.net/browse/WG-268)
1. To be tested with https://github.com/TACC-Cloud/geoapi/pull/206
2. Ensure log-in works.   (`/login` or `/logout`
3. You could logout and then go to a URL of a map project and ensure after login you end up at that project).
4. You could change the "is-expired" buffer (in angular/src/app/models/models.ts) from 5 minutes to 3hrs and 55 minutes ( 14100000 ms).  So then the token which lasts 4 hours is updated after just 5 minutes of uses and you can see the login happening again.  
5. On server side, you could also change: …
=> task/WG-268: add authentification to backend

react/package-lock.json, react/package.json, react/src/__fixtures__/appConfigurationFixture.ts, react/src/__fixtures__/authStateFixtures.ts, react/src/components/CreateMapModal/CreateMapModal.test.tsx, react/src/components/Projects/ProjectListing.tsx, react/src/constants/routes.ts, react/src/core-components/SectionMessage/SectionMessage.test.jsx, react/src/hooks/environment/useAppConfiguration.ts, react/src/hooks/index.ts, react/src/hooks/projects/useProjects.ts, react/src/hooks/systems/useSystems.ts, react/src/hooks/user/index.ts, react/src/hooks/user/useAuthenticatedUser.ts, react/src/hooks/user/useEnsureAuthenticatedUserHasValidTapisToken.ts, react/src/pages/Callback/Callback.tsx, react/src/pages/Login/Login.test.tsx, react/src/pages/Login/Login.tsx, react/src/redux/authSlice.ts, react/src/requests.test.ts, react/src/requests.ts, react/src/secret_local.example.ts, react/src/types/auth.ts, react/src/types/environment.ts, react/src/utils/authUtils.test.ts, react/src/utils/authUtils.ts
This PR updates react client to use tapisv3:
* uses new auth flow.
* updates requests to tapis
Also in this PR is the following:
* adds on click behavior to navigate to map project (to ease testing)
* fixes one warning in tests
* [WG-366](https://tacc-main.atlassian.net/browse/WG-366)
1. ** do not use dev geoapi as backend as still down; use Staging or Production in `react/src/secret_local.ts`  **
2. Run app and look at project listing.
3. Click on an existing project and see that map is populated with features as expected
=> task/WG-366: update react frontend to use tapisv3

angular/src/app/components/modal-create-project/modal-create-project.component.ts, angular/src/app/services/projects.service.ts
This PR improves the error message when trying to create a duplicate syncing project.
This matches the error message handling we already have in the react client.
* [WG-XYZ](https://tacc-main.atlassian.net/browse/WG-295)
=> task/WG-295: improve error message when duplicate syncing project

react/jest.setup.ts, react/src/AppRouter.tsx, react/src/components/AssetsPanel/AssetsPanel.test.tsx, react/src/components/AssetsPanel/AssetsPanel.tsx, react/src/components/DeleteMapModal/DeleteMapModal.tsx, react/src/components/FeatureFileTree/FeatureFileTree.test.tsx, react/src/components/FeatureFileTree/FeatureFileTree.tsx, react/src/components/ManageMapProjectModal/ManageMapProjectModal.tsx, react/src/components/MapProjectNavBar/MapProjectNavBar.test.tsx, react/src/components/MapProjectNavBar/MapProjectNavBar.tsx, react/src/hooks/features/useDeleteFeature.ts, react/src/hooks/features/useFeatures.ts, react/src/hooks/projects/useProjects.ts, react/src/hooks/tileServers/useTileServers.ts, react/src/pages/MapProject/MapProject.tsx, react/src/requests.ts, react/src/test/testUtil.tsx
This PR:
* updates useDeleteProject to use variables version of useDelete
* renames `isPublic` to `isPublicView` (to make it clear that we are talking about viewing a public map and not just if a map is public)
* makes the downloaded file have the same name as the map (from 
* updates some tests to use msw (https://github.com/TACC-Cloud/hazmapper/pull/280)
* [WG-238](https://tacc-main.atlassian.net/browse/WG-238)
=> Task/WG-238: follow on

angular/src/app/components/main-welcome/main-welcome.component.html, angular/src/app/components/main-welcome/main-welcome.component.styl, angular/src/app/components/main-welcome/main-welcome.component.ts
This reverts commit dedc5c8df142bc82dffda5035f51830327c538c2 and removes the temp banner we had displayed since the TapisV3 migration
=> Revert "Hotfix/banner for aug7 (#249)"

react/src/__fixtures__/featuresFixture.ts, react/src/utils/featureTreeUtils.test.ts, react/src/utils/featureTreeUtils.ts
Duplicate file paths were not being shown in feature tree
None
1.  See unit tests
=> hotfix:  show duplicate file paths in feature tree

react/src/components/Map/Map.tsx
This PR updates react-leaflet MapContainer configuration to enable preferCanvas for improved rendering performance with dense map features.
None
1. No testing needed but you could get a map with lots of non-point features and then check performance scrolling in the map with/without this change. and confirm that selecting works etc.
=> hotfix: enable `preferCanvas` option in MapContainer

react/package-lock.json, react/src/common_components/Button/Button.module.css, react/src/common_components/Button/Button.tsx, react/src/common_components/Button/index.ts, react/src/common_components/Icon/Icon.tsx, react/src/common_components/Icon/index.ts, react/src/common_components/Spinner/Spinner.module.css, react/src/common_components/Spinner/Spinner.tsx, react/src/common_components/Spinner/index.ts, react/src/common_components/index.ts, react/src/index.tsx
- Add global styling token for antd components
- Updates antd and resolves some medium vulnerabilities in npm packages
- Adds a few common components for future use
* [WG-394](https://tacc-main.atlassian.net/browse/WG-394)
=> task/WG-394: Global Antd styling

react/src/components/AssetsPanel/AssetsPanel.test.tsx, react/src/components/AssetsPanel/AssetsPanel.tsx, react/src/components/FileBrowserModal/FileBrowserModal.test.tsx, react/src/components/FileBrowserModal/FileBrowserModal.tsx, react/src/components/FileBrowserModal/index.ts, react/src/components/Files/FileListing.test.tsx, react/src/components/Files/FileListing.tsx, react/src/hooks/features/index.ts, react/src/hooks/features/useImportFeature.ts, react/src/test/handlers.ts, react/src/types/file.ts, react/src/utils/fileUtils.ts
Modal for importing assets from designsafe
* [WG-387](https://tacc-main.atlassian.net/browse/WG-387)
1. Load a map and click Import from Designsafe button
TODO:
=> WIP - WG-387 - Import from Designsafe Modal

react/src/hooks/environment/getLocalAppConfiguration.ts, react/src/secret_local.example.ts, react/src/types/environment.ts
Allow user to set which DesignSafe site to use in local dev
Note: LocalAppConfiguration.designSafePortal is optional and defaults to PPRD.
=> Hotfix/allow user to set which DesignSafe site to use in local dev

react/src/components/CreateMapModal/CreateMapModal.module.css, react/src/components/CreateMapModal/CreateMapModal.test.tsx, react/src/components/CreateMapModal/CreateMapModal.tsx, react/src/components/Files/FileListing.tsx, react/src/components/Projects/ProjectListing.tsx, react/src/index.tsx
- Fix form state on submit, refactored to use react hook form
- UI adjustments to use Ant components
* [WG-434](https://tacc-main.atlassian.net/browse/WG-434)
1. Open create map modal
2. Adjust all fields, select a new system, change path
3. Confirm all UI fields update as expected
4. Confirm form is submitted with map data created as expected
=> bug/WG-434: Refactor Create Map modal

react/src/components/CreateMapModal/CreateMapModal.tsx, react/src/components/ManageMapProjectPanel/SaveTabContent.tsx
Fix system path during project creation. 
This PR also makes some small changes to the display of the projects' system/path in the manage panel.
* [WG-436](https://tacc-main.atlassian.net/browse/WG-436)
1. Create a new map in subfolder in My Data or in a project
2. Confirm that this works as expected by checking POST or the links or the location of the .hazmapper file. Also, check the display/links of related DS project are correct in the Manage Panel.
=> fix/WG-436: use system path during project creation

react/package-lock.json, react/package.json, react/src/components/DeleteMapModal/DeleteMapModal.test.tsx, react/src/components/DeleteMapModal/DeleteMapModal.tsx, react/src/components/FiltersPanel/Filter.tsx, react/src/components/ManageMapProjectPanel/PublicTabContent.tsx, react/src/components/QuestionnaireModal/QuestionnaireModal.module.css, react/src/components/QuestionnaireModal/QuestionnaireModal.tsx, react/src/hooks/features/useFeatures.ts, react/src/pages/Callback/Callback.test.tsx, react/src/pages/Callback/Callback.tsx, react/src/pages/MapProject/MapProject.module.css, react/src/pages/MapProject/MapProject.tsx, react/src/requests.ts
Various UI/UX fixes from the Feb 18 testing session.
* [WG-441](https://tacc-main.atlassian.net/browse/WG-441)
* [WG-457](https://tacc-main.atlassian.net/browse/WG-457)
* [WG-445](https://tacc-main.atlassian.net/browse/WG-445)
* [WG-443](https://tacc-main.atlassian.net/browse/WG-443)
- add loading spinner on login callback layout
- public project links now stay within container when long
- public project links now link directly to the project, with no panel selected
- delete map modal and questionnaire modal refactored to antd; close button fixed.
- refactor datepicker to antd; add visually clear tooltip
- fix re-render issue on filter change
- add bottom margin to asset detail in order to show leaflet zoom buttons
1. Test each of the above and ensure they work as expected
Do we like the …
=> Testing Session UI/UX fixes

react/src/__fixtures__/appConfigurationFixture.ts, react/src/components/ManageMapProjectPanel/ManageMapProjectPanel.test.tsx, react/src/components/ManageMapProjectPanel/MapTabContent.test.tsx, react/src/components/ManageMapProjectPanel/MapTabContent.tsx, react/src/hooks/environment/getLocalAppConfiguration.ts, react/src/hooks/environment/useAppConfiguration.ts, react/src/hooks/environment/utils.ts, react/src/types/environment.ts
This implements navigating to taggit.  Note taggit doesn't have project-specific routes so we have to write to local storage. 
Also tweaked the `switches between tabs correctly` test as all components in tabs are rendered so reworked to check if active component was in active tab.
* [WG-430](https://tacc-main.atlassian.net/browse/WG-430)
It’s slightly difficult to test in local development since we don’t currently run Taggit alongside Hazmapper.
1. Run unit tests
2. Set debugger before `navigate(config.taggitUrl);` to see that it would navigate to `localhost:/taggit-local`
=> task/WG-430: implement taggit gallery navigation

react/src/components/CreateMapModal/CreateMapModal.tsx, react/src/components/ManageMapProjectPanel/SaveTabContent.tsx, react/src/utils/fileUtils.ts
Create common util, `renderFilePathLabel` for human readable paths
* [WG-439](https://tacc-main.atlassian.net/browse/WG-439)
* [WG-437](https://tacc-main.atlassian.net/browse/WG-437)
1. Check out the Create Map Modal and the "Save" tab of the manage map panel, and confirm paths look good
=> task/WG-439, task/WG-437: Use system path util

react/index.html, react/src/hooks/environment/useAppConfiguration.ts, react/src/hooks/environment/utils.ts
Add support for `hazmapper-tmp`.
See the related  https://github.com/TACC/Core-Portal-Deployments/pull/83
* [WG-225](https://tacc-main.atlassian.net/browse/WG-225)
1. See https://github.com/TACC/Core-Portal-Deployments/pull/83
2. This is deployed on staging geoapi-services
=> task/WG-225: support hazmapper-tmp

react/package-lock.json, react/package.json, react/src/components/PointCloudsPanel/PointCloudPanel.tsx, react/src/components/PointCloudsPanel/PointCloudPanelListItem.tsx
Improve point cloud panel performance for large lists:
- Add a loading spinner while fetching point clouds
- Use a virtual list for efficient rendering
* [WG-473](https://tacc-main.atlassian.net/browse/WG-473)
- Refactored the point cloud list item into a separate component: PointCloudPanelListItem.tsx
- Added a loading spinner while fetching point clouds
- Integrated FixedSizeList from react-window for efficient list rendering
in "react/src/secret_local.ts" have the following to test with staging:
```
import {
DesignSafePortalEnvironment,
GeoapiBackendEnvironment,
LocalAppConfiguration,
} from '@hazmapper/types';
export const localDevelopmentConfiguration: LocalAppConfiguration = {
geoapiBackend: GeoapiBackendEnvironment.Staging,
designSafePortal: DesignSafePortalEnvironment.PPRD
};
``` …
=> task/WG-473: Use loading spinner and virtual list in point cloud panel

react/package-lock.json, react/src/__fixtures__/projectFixtures.ts, react/src/components/FileBrowserModal/FileBrowserModal.tsx, react/src/components/Files/FileListing.test.tsx, react/src/components/Files/FileListing.tsx, react/src/components/Systems/SystemSelect.test.tsx, react/src/components/Systems/SystemSelect.tsx, react/src/hooks/designsafe/index.ts, react/src/hooks/designsafe/useDesignSafeProjects.ts, react/src/hooks/index.ts, react/src/hooks/projects/index.ts, react/src/hooks/projects/useProjects.ts, react/src/hooks/systems/useSystems.ts, react/src/test/handlers.ts, react/src/types/index.ts, react/src/types/projects.ts, react/src/types/projectsDesignSafe.ts
This PR uses DesignSafe endpoints for published projects listings. 
This PR also makes some minor changes:
* Refactor designsafe-related types and hooks into own files
* Don't retry systems automatically (not relate to this PR but was an issue)
* destroyOnClose is replaced by destroyOnHidden for antd's Modal
* [WG-468](https://tacc-main.atlassian.net/browse/WG-468)
1. Use staging Hazmapper (which uses pprd.designsafe-ci)
2. Test that you can find files in publications.  Try the newest publications from recent testing session (on pprd.designsafe-ci) and older ones
=> Task/WG-468: use DesignSafe endpoint for published projects listings
