TACC-Cloud/hazmapper

src/app/app.module.ts
src/app/components/control-bar/control-bar.component.ts
src/app/components/modal-create-point-cloud/modal-create-point-cloud.component.html
src/app/components/modal-point-cloud-info/modal-point-cloud-info.component.html
src/app/components/modal-point-cloud-info/modal-point-cloud-info.component.spec.ts
src/app/components/modal-point-cloud-info/modal-point-cloud-info.component.styl
src/app/components/modal-point-cloud-info/modal-point-cloud-info.component.ts
src/app/components/point-cloud-panel-row/point-cloud-panel-row.component.html
src/app/components/point-cloud-panel-row/point-cloud-panel-row.component.ts
src/app/components/point-clouds-panel/point-clouds-panel.component.html
src/app/components/point-clouds-panel/point-clouds-panel.component.ts
src/app/models/models.ts
src/app/services/geo-data.service.ts

Improve point cloud panel.  Add modal to show details about point cloud. 
Requires https://github.com/TACC-Cloud/geoapi/pull/10

Improve point cloud panel

---

src/app/components/asset-detail/asset-detail.component.html
src/app/components/asset-detail/asset-detail.component.ts

Adds iframe to show preview of potree-processed point cloud. 
Requires: https://github.com/TACC-Cloud/geoapi/pull/9

Add preview iframe to point cloud panel

---

src/app/models/models.ts
src/app/services/agave-systems.service.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Use projects endpoint from DesignSafe to get project listing

Use projects endpoint from DesignSafe

---

src/app/components/control-bar/control-bar.component.html
src/app/components/control-bar/control-bar.component.ts
src/app/services/geo-data.service.ts

Remove auto reload and use notifications to trigger update of project data

Use notifications to trigger update of project data

---

src/environments/environment.prod.ts

Remove ending slash to api url

---

src/app/app.module.ts
src/app/components/user-row/user-row.component.html
src/app/components/user-row/user-row.component.spec.ts
src/app/components/user-row/user-row.component.ts
src/app/components/users-panel/users-panel.component.html
src/app/components/users-panel/users-panel.component.ts
src/app/services/projects.service.ts

Add user deletion to front end.
Dependent on https://github.com/TACC-Cloud/geoapi/pull/26

Add user deletion to front end. 

---

package-lock.json
package.json
src/app/components/assets-panel/assets-panel.component.ts
src/app/components/file-browser/file-browser.component.html
src/app/components/file-browser/file-browser.component.ts
src/app/services/tapis-files.service.ts

Fixes DES-1649 by 
* adding infinite scrolling to data browser
* uses newer ng-tapis

Add infinite scrolling to data browser

---

src/app/app.interceptors.ts
src/app/components/file-browser/file-browser.component.html
src/app/components/file-browser/file-browser.component.ts
src/app/components/modal-create-project/modal-create-project.component.html
src/app/services/projects.service.ts

Related to DES-1532, this PR alters hides community data or published projects and alters error handling for observable/rapid projects.
* [DES-1532](https://jira.tacc.utexas.edu/browse/DES-1532)
* Hide published projects/community data folders from observable projects
* Display either a general error or an existing project error

Des 1532 project users fix error restrict systems

---

.travis.yml
README.md
src/app/components/modal-file-browser/modal-file-browser.component.spec.ts
src/environments/environment.prod.ts

Fix unit tests
* [DES-1713](https://jira.tacc.utexas.edu/browse/DES-1713)
1. Run tests locally

Fix unit tests and run in CI

---

src/environments/environment.prod.ts

Update client id for https://hazmapper.tacc.utexas.edu/hazmapper/

Update client id

---

src/app/components/main-welcome/main-welcome.component.html

Adds higher resolution image for the welcome page
* [DES-1895](https://jira.tacc.utexas.edu/browse/DES-1895)
Added the images to assets and changed the image source for the main logo.
1. Confirm that image is higher resolution.
N/A

Higher resolution image for welcome page.

---

src/app/components/control-bar/control-bar.component.ts
src/app/components/filters-panel/filters-panel.component.ts
src/app/components/main-project/main-project.component.ts
src/app/components/point-clouds-panel/point-clouds-panel.component.ts
src/app/services/geo-data.service.ts
src/app/services/projects.service.ts

Use public-projects routes provided by https://github.com/TACC-Cloud/geoapi/pull/56 when viewing a public map.
* [DES-1946](https://jira.tacc.utexas.edu/browse/DES-1946)
* Use public-projects map when accessing public maps
1. Run locally with  https://github.com/TACC-Cloud/geoapi/pull/56
2. Or run/test on staging environment (when that has been configured with auth type of None for these routes)

Use public project routes when accessing public view of map

---

CHANGELOG.md

Make releases and add CHANGELOG.md
* [DES-1951](https://jira.tacc.utexas.edu/browse/DES-1951)
1. Review changelog
2. Review releases on Github  (https://github.com/TACC-Cloud/hazmapper/releases)
I did not create a release for 2.0 and left details of 2.1 blank.

Add changelog/release notes

---

package-lock.json
src/app/components/asset-detail/asset-detail.component.html

* [DES-9999](https://jira.tacc.utexas.edu/browse/DES-9999)
1.

remove point cloud preview since iframes are not allowed

---

README.md
src/app/components/asset-detail/asset-detail.component.html
src/app/services/env.service.ts

* Add point cloud preview
* use Hazmapper.local
* [DES-2054](https://jira.tacc.utexas.edu/browse/DES-205)
1. 
TODO

Add hazmapper.local client and add back preview

---

CHANGELOG.md

Update changelog for 2.5 release

---

CHANGELOG.md

Make 2.6 release notes

---

CHANGELOG.md
src/app/components/main-welcome/main-welcome.component.html

Make 2.8 release notes

---

.github/workflows/main.yml

adjust workflow to use angular folder

Task/DES- 2131: adjust workflow to use angular folder

---

CHANGELOG.md
angular/src/app/components/main-welcome/main-welcome.component.html

Make 2.9 release notes

---

CHANGELOG.md

Update changelog for v2.11

---

react/src/components/AppRouter.tsx
react/src/components/Authentication/Callback/Callback.test.tsx
react/src/components/Authentication/Callback/Callback.tsx
react/src/components/Authentication/Login/Login.test.tsx
react/src/components/Authentication/Login/Login.tsx
react/src/components/Authentication/Logout/Logout.test.tsx
react/src/components/Authentication/Logout/Logout.tsx
react/src/components/MainMenu/MainMenu.test.tsx
react/src/components/MainMenu/MainMenu.tsx
react/src/components/MainMenu/index.ts
react/src/components/MapProject/MapProject.tsx
react/src/components/Menu/Menu.test.tsx
react/src/components/Menu/Menu.tsx
react/src/redux/api/geoapi.ts
react/src/redux/authSlice.ts
react/src/redux/reducers/reducers.ts
react/src/redux/store.ts
react/src/utils/authUtils.ts

Add login/logout/callback
* [WG-15](https://jira.tacc.utexas.edu/browse/WG-15)
1. go to any protected route to login (like `http://localhost:4200/project/2caa321b-3f6a-4faf-b1a7-9717261aec60`)
2. see that you go to tapis auth and then to callback and then to your desired route (like http://localhost:4200/project/2caa321b-3f6a-4faf-b1a7-9717261aec60)
3. go to http://localhost:4200/logout to see if you can login again
TBD
- either add better unit tests or note what they should be in a ticket

task/WG-15: add login

---

CHANGELOG.md

Make 2.13 release

---

angular/src/app/components/main-welcome/main-welcome.component.ts

Fix bug in condition related to adding info from DS projects.

hotifx: fix condition for adding info from related DS projects

---

angular/src/app/components/file-browser/file-browser.component.ts

Fix regression caused by #148.

Fix projects listing from DS

---

angular/src/app/services/agave-systems.service.ts

Fix another regression caused by https://github.com/TACC-Cloud/hazmapper/pull/148.
1. Load map project and check that Manage panel works as expected.

hotfix: fix check of ds projects

---

CHANGELOG.md

Add 2.14 changelog

---

CHANGELOG.md

Make v2.15 release notes

---

angular/src/app/components/asset-detail/asset-detail.component.ts
angular/src/app/components/questionnaire-detail/questionnaire-detail.component.ts

Fix the questionnaire detail panel as the component was not being updated when the active feature changed
This PR also updates asset-detail.component.ts for the case where there is no active feature.
* [WG-188](https://jira.tacc.utexas.edu/browse/WG-188)
1. Ensure the right panel is properly updated when selecting between different photo features or questionnaire features
2. Ensure no errors in console when user deselect a feature

task/WG-188: fix questionnaire detail panel

---

angular/src/app/app.interceptors.ts

Disable custom headers
* [WG-189](https://jira.tacc.utexas.edu/browse/WG-189)

hotfix/WG-189: disable custom headers

---

.github/pull_request_template.md

Updating PR template links to use the new cloud system links
* [WG-194](https://tacc-main.atlassian.net/browse/WG-194)
- Changed the link in the templates to use the new cloud system links
1. When creating a PR, check the template and make sure the new link format (under "Related Jira Tickets") is correct with the new cloud system link

task/WG-194: Updating Template Links to New Cloud System Links

---

CHANGELOG.md

Update CHANGELOG for v2.16

---

CHANGELOG.md
angular/src/app/components/main-welcome/main-welcome.component.html

Update Changelog for v2.17 release

Update Changelog for v2.17 release

---

README.md

Update README.md:
* remove jwt info as no longer needed
* update info on geoapi with react client

Hotfix/update README.md about jwt

---

.gitignore
react/src/components/FiltersPanel/Filter.tsx
react/src/components/FiltersPanel/Filters.module.css
react/src/hooks/features/useFeatures.ts
react/src/pages/MapProject/MapProject.tsx

Enables toggleable date range filter.
* [WG-277](https://tacc-main.atlassian.net/browse/WG-277)
1. Click "Enable Date Range Filter" button and change date range
2. Confirm assets returned are within range
3. Disable filter by clicking "Disable Date Range Filter"
4. Confirm assets returned are without date boundary

task/WG-277: Implement Date Range Filter

---

react/src/requests.ts

Minor change for using `params`

Update packages  use params for analytics change

---

react/src/components/HeaderNavBar/HeaderNavBar.tsx
react/src/pages/MainMenu/MainMenu.tsx

update image import syntax for vite asset handling

hotfix: update image import syntax for vite asset handling

---

react/src/components/CreateLayerModal/CreateLayerModal.tsx
react/src/components/PointCloudsPanel/PointCloudCreateModal.tsx
react/src/components/PointCloudsPanel/PointCloudInfoModal.tsx
react/src/index.tsx

Set zindex for antd popups like modals

Set zindex for antd popups like modals

---

react/package-lock.json
react/package.json

Bump tacc/core-components to 0.0.3

Task/use core components 0.0.3

---

react/src/components/ManageMapProjectPanel/PublicTabContent.tsx

Task/WG-243: manage project public path change

---

angular/src/app/services/agave-systems.service.ts

Get all systems (via -1) from tapis
* [WG-482](https://tacc-main.atlassian.net/browse/WG-482)

task/WG-482: Get all systems (via -1) from tapis

---

CHANGELOG.md

Updates changelog with v2.2 changes for hazmapper project only
1.

task/CHANGELOG.MD v2.2

---

angular/src/app/components/callback/callback.component.ts
react/src/pages/Callback/Callback.tsx

Remove query-param approach for auth flow.  Now using hash.
* [WG-493](https://tacc-main.atlassian.net/browse/WG-493)
1. Just a code review is sufficient.

task/WG-493: Remove query-param approach for auth flow

---

react/jest.config.cjs
react/package-lock.json
react/package.json
react/src/components/CreateMapModal/CreateMapModal.test.tsx
react/src/components/FileBrowserModal/FileBrowserModal.test.tsx
react/src/components/Files/FileListing.test.tsx
react/src/components/Files/FileListing.tsx
react/src/utils/fileUtils.ts

Change the chonky package to use [@aperturerobotics/chonky](https://www.npmjs.com/package/@aperturerobotics/chonky). This is an updated fork of the original Chonky package with updated dependencies so we don't see any deprecation warnings
* [WG-426](https://tacc-main.atlassian.net/browse/WG-426)
1. Test file browser functionality and ensure everything works as expected

task/WG-426 - Chonky Package Update

---

react/src/components/CreateMapModal/CreateMapModal.test.tsx
react/src/components/CreateMapModal/CreateMapModal.tsx
react/src/components/Files/FileListing.test.tsx
react/src/components/Files/FileListing.tsx
react/src/components/ManageMapProjectPanel/SaveTabContent.tsx
react/src/components/MapProjectAccessError/MapProjectAccessError.tsx
react/src/hooks/user/useAuthenticatedUser.ts

Low priority PR to do some housekeeping and remove `data` from `useAuthenticatedUser`
None
1. Confirm that things still work as expected
2. Maybe, confirm that you can load data from My Data or from a DS project.
3. (FYI: if https://pprd.designsafe-ci.org has been redeployed lately, you'll need to login first)

hotfix/remove data from useAuthenticatedUser

---

react/index.html
react/src/hooks/environment/utils.ts

Remove hazmapper-tmp from frontend
* [WG-513](https://tacc-main.atlassian.net/browse/WG-513)
1.  Confirm it still works.

task/WG-513: remove hazmapper-tmp
